apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: dev
type: Opaque
data:
  SPRING_ZIPKIN_BASEURL: aHR0cDovL3ppcGtpbi1zZXJ2aWNlLmRldi5zdmMuY2x1c3Rlci5sb2NhbDo5NDEx
  eureka.client.service-url.default-zone: aHR0cDovL3NlcnZpY2UtcmVnaXN0cnkuZGV2LnN2Yy5jbHVzdGVyLmxvY2FsOjg3NjE=
  eureka.client.service-url.defaultZone: aHR0cDovL3NlcnZpY2UtcmVnaXN0cnkuZGV2LnN2Yy5jbHVzdGVyLmxvY2FsOjg3NjEvZXVyZWth
  management.zipkin.tracing.endpoint: aHR0cDovL3ppcGtpbi5kZXYuc3ZjLmNsdXN0ZXIubG9jYWw6OTQxMS9hcGkvdjIvc3BhbnM=
  spring.data.mongodb.database: TWFya2V0TWFw
  spring.data.mongodb.database.pull: cHVsbF9kaXN0cmlidXRpb25fZGI=
  spring.data.mongodb.uri: bW9uZ29kYitzcnY6Ly9kYXR0YWJoYXJkZTplanFVVWtZYlRGRlppbkJVQG1hcmtldG1hcC55Zm92ODBuLm1vbmdvZGIubmV0Lw==
  spring.data.redis.host: cmVkaXMtZGV2LW1hc3Rlci5kZXYuc3ZjLmNsdXN0ZXIubG9jYWw=
  spring.data.redis.password: VVFlWDdhWG40VQ==
  spring.zipkin.base-url: aHR0cDovL3ppcGtpbi1zZXJ2aWNlLmRldi5zdmMuY2x1c3Rlci5sb2NhbDo5NDEx
  spring.zipkin.baseUrl: aHR0cDovL3ppcGtpbi1zZXJ2aWNlLmRldi5zdmMuY2x1c3Rlci5sb2NhbDo5NDEx
