apiVersion: apps/v1
kind: Deployment
metadata:
  name: flow-service
  namespace: dev
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: flow-service
  template:
    metadata:
      labels:
        app: flow-service
    spec:
      containers:
        - name: api-flow-service
          image: asia-south2-docker.pkg.dev/market-map-dev/service-registry/flow_service:latest
          imagePullPolicy: 'Always'
          ports:
            - containerPort: 8080 
          env:
            - name: spring.data.mongodb.uri
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: spring.data.mongodb.uri
            - name: spring.data.mongodb.database.pull
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: spring.data.mongodb.database.pull
            - name: eureka.client.service-url.defaultZone
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: eureka.client.service-url.defaultZone
            - name: spring.data.redis.host
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: spring.data.redis.host
            - name: spring.data.redis.password
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: spring.data.redis.password
            - name: management.zipkin.tracing.endpoint
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: management.zipkin.tracing.endpoint
---
apiVersion: v1
kind: Service
metadata:
  name: flow-service
  namespace: dev
spec:
  ports:
    - port: 8080
  selector:
    app: flow-service
