spring:
  application:
    name: pull-distribution-system
  data:
    mongodb:
      uri: mongodb://localhost:27017/pull_distribution_db
      database:
        pull: pull_distribution_db
      auto-index-creation: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
  cloud:
    compatibility-verifier:
      enabled: false
  mvc:
    # Disable static resource handling for API paths
    static-path-pattern: /static/**
    # Ensure proper path matching
    pathmatch:
      matching-strategy: ant_path_matcher
    web:
      resources:
        # Only serve static resources from specific paths
        static-locations: classpath:/static/
        add-mappings: false  # Disable default static resource mappings

  server:
    # Ensure proper forwarded headers handling
    forward-headers-strategy: framework
    # Handle X-Forwarded-* headers from ingress
    use-forward-headers: true

server:
  port: 8080

identity:
  service:
    url: http://localhost:8282

logging:
  level:
    org.springframework: INFO
    com.onified.distribute: DEBUG

# Minimal Swagger Configuration
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
