spring:
  application:
    name: pull-distribution-system
  data:
    mongodb:
      uri: mongodb://localhost:27017/pull_distribution_db
      database:
        pull: pull_distribution_db
      auto-index-creation: true
  jackson:
    serialization:
      write-dates-as-timestamps: false
  cloud:
    compatibility-verifier:
      enabled: false
sap:
  api:
    url: https://l550274-iflmap.hcisbp.ae1.hana.ondemand.com/http/Towel_StockDetail
    authorization: Basic dmluYXluYW5kYUB0cmlkZW50aW5kaWEuY29tOkNvbUAxNTY3ODk=

  server:
    # Ensure proper forwarded headers handling
    forward-headers-strategy: framework
    # Handle X-Forwarded-* headers from ingress
    use-forward-headers: true

server:
  port: 8080

identity:
  service:
    url: http://localhost:8282

logging:
  level:
    org.springframework: INFO
    com.onified.distribute: DEBUG

# Minimal Swagger Configuration
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
